name: Update axe-core
description: Update axe-core to its latest stable version
outputs:
  version:
    description: Version axe-core was updated to
    value: ${{ steps.main.outputs.version }}
  previous_version:
    description: Version of axe-core prior to updating
    value: ${{ steps.main.outputs.previous_version }}
runs:
  using: composite
  steps:
    - shell: bash
      run: ./update.sh
      id: main
